// Generated by alioth-center database-columns. DO NOT EDIT.
// Generated by alioth-center database-columns. DO NOT EDIT.
// Generated by alioth-center database-columns. DO NOT EDIT.
package model

type accountCols struct {
	ID          string
	Integration string
	UserID      string
	Account     string
	CreatedAt   string
	UpdatedAt   string
}

var AccountCols = &accountCols{
	ID:          "id",
	Integration: "integration",
	UserID:      "user_id",
	Account:     "account",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}
