// Generated by alioth-center database-columns. DO NOT EDIT.
// Generated by alioth-center database-columns. DO NOT EDIT.
// Generated by alioth-center database-columns. DO NOT EDIT.
package model

type clientCols struct {
	ID        string
	Name      string
	Secret    string
	CreatedAt string
	UpdatedAt string
}

var ClientCols = &clientCols{
	ID:        "id",
	Name:      "name",
	Secret:    "secret",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}
