// Code generated by alioth-center/database-columns. DO NOT EDIT.
// Code generated by alioth-center/database-columns. DO NOT EDIT.
// Code generated by alioth-center/database-columns. DO NOT EDIT.

package model

type integrationCols struct {
	ID        string
	Name      string
	Secret1   string
	Secret2   string
	Secret3   string
	Secret4   string
	CreatedAt string
	UpdatedAt string
}

var IntegrationCols = &integrationCols{
	ID:        "id",
	Name:      "name",
	Secret1:   "secret1",
	Secret2:   "secret2",
	Secret3:   "secret3",
	Secret4:   "secret4",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}
