// Generated by alioth-center database-columns. DO NOT EDIT.
// Generated by alioth-center database-columns. DO NOT EDIT.
// Generated by alioth-center database-columns. DO NOT EDIT.
package model

type templateCols struct {
	ID        string
	Name      string
	Content   string
	Arguments string
	CreatedAt string
	UpdatedAt string
}

var TemplateCols = &templateCols{
	ID:        "id",
	Name:      "name",
	Content:   "content",
	Arguments: "arguments",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}
