// Generated by alioth-center database-columns. DO NOT EDIT.
// Generated by alioth-center database-columns. DO NOT EDIT.
// Generated by alioth-center database-columns. DO NOT EDIT.
package model

type userCols struct {
	ID        string
	Type      string
	Name      string
	CreatedAt string
	UpdatedAt string
}

var UserCols = &userCols{
	ID:        "id",
	Type:      "type",
	Name:      "name",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}
